### ISSUE TITLE
Add missing conversion tests for Lch and Lab

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#107]
There are no tests for conversion from `Lch` and `Lab` to other spaces in the test suite in `palette/tests/convert`. They were not added, due to problems with scaling and hue, but the scaling should be correct now, so I hope it should be possible to at least add some tests.

**Comment by CGUTA** [comment]
Hello @Ogeon

I would like to give this a go if that is ok with you?

I see that the data is already in colormine.csv and that the patterns will be similar to the tests for the other colors as far as i can tell.

**Comment by Ogeon** [comment]
Sure go ahead! Let me know if you run into any problems.

**Comment by CGUTA** [comment]
The conversion from xyz to lab goes ok for colormine data if the epsilon is increased to 0.1
The conversion for yxy needs a bigger epsilon between 5.0 (fail) and 10.0 (pass).

With a CIExyY input:

|Y | x | y|
| - | - | - |
|92.88 | 0.3 | 0.32|

And using the colormine csv as gold standard for the CIE Lab these are the results using palette and the colormine converter http://colormine.org/convert/lab-to-yxy (converts both ways):

|color_data|L|a|b|RMSE|
|-|-|-|-|-|
colormine_csv|97,18|-1.34|-4.27|0.0
colormine_web|97.01|-2.75|-4.40|0.61|
palette|97.17|2.22|-5.72|0.95|

To give an idea of Epsilon vs RMSE the from XYZ conversion generated a Lab result that needs an epsilon of 0.1 to pass. This has a RMSE (root mean squared error) of 0.004.

From this I conclude that is a problematic conversion also for the colormine converters so it should not be too uncareful to increase the epsilon to make the test pass.
