### ISSUE TITLE
Find a good way to decouple the alpha channel

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#11]
Having the alpha channel being affected by operations as arithmetics isn't always what you want, so it would be nice if it can be separated from the color types in a good, convenient and intuitive enough way. This is also useful for when the alpha channel is insignificant (always 1.0), to save some space. I have been thinking about an `Alpha<C>` wrapper type along these lines:

```rust
struct Alpha<C> {
    pub color: C,
    pub alpha: f32,
}

impl<C: Mix> Mix for Alpha<C> {
    //...
}

//etc.
```

and maybe even make it dereference as the color type `C`. I don't know if this will end up being too inconvenient or not, and better solutions are always welcome. I'll see if I can figure something else out before making a test implementation.

**Comment by sidred** [comment]
I was thinking to use 2 separate structs: 

```

pub struct XYZ<T> {
    pub x: T,
    pub y: T,
    pub z: T,
}

pub struct XYZa<T> {
    pub x: T,
    pub y: T,
    pub z: T,
    pub a: f32,
}
```


and then have a color trait

```
#[allow(non_camel_case_types,non_snake_case)]
pub trait xyYColor<T:Float> {
    fn get_x(&self) -> T;
    fn get_y(&self) -> T;
    fn get_Y(&self) -> T;
}

```
Then we can have all the conversions, mixing etc etc. generic on the color trait and will be implemented automatically on both the structs. Probably a bit more work, but will have a simpler api for the user.

**Comment by Ogeon** [comment]
Possibly. That will result in a lot of traits, not to mention duplication, but it may work in the end. The `Alpha` type won't really be complicated, in comparison, since we can make type aliases (such as `type Rgba = Alpha<Rgb>;`). I expect the user to end up with two types anyway, but only one implementation for each space + one for the `Alpha` type. I still haven't tested it, though, so I don't know how it will be.

**Comment by sidred** [comment]
We'll have 2 types either way. But with the Rgba = Alpha\<Rgb\>, you'll have to access the individual color by ```my_var.color.red``` vs ```my_var.red``` for Rgb struct. Not sure if it matters too much.

Its pretty much going to be the same amount of work. Both will need additional traits for converting Rgba -> Laba vs Rgb -> Lab etc.

**Comment by Ogeon** [comment]
> `my_var.color.red` vs `my_var.red`

That's what I thought `Deref` and `DerefMut` could help with. Here is a simple case with the same structure: http://is.gd/vjZBpI

> Its pretty much going to be the same amount of work. Both will need additional traits for converting Rgba -> Laba vs Rgb -> Lab etc.

Depends on if this will work:

```rust
impl<T, U> From<Alpha<T>> for Alpha<U> where U: From<T> {
    //...
}
```

**Comment by sidred** [comment]
Makes sense. Then this is better that the 2 structs.

**Comment by Ogeon** [comment]
My bets are currently on the `Alpha` type, but we'll see. It may have some deal breaking properties that we don't yet know about. That's what a test implementation will tell us.

**Comment by sidred** [comment]
Do you want me to implement the f32/f64 traits and conversions first? Or do it after the alpha change? I am trying to think what is easier. For now I think I will just implement it on the structs as is.

**Comment by Ogeon** [comment]
I don't really think the order matters, but this one may need some more planning and testing. Extracting the alpha component will also have a larger impact on the general API.

**Comment by sidred** [comment]
Ok i'll implement it and submit a pr.

**Comment by Ogeon** [comment]
:+1:

**Comment by Ogeon** [comment]
I have been experimenting a bit with this and it goes mostly well, except for the fact that `impl<T, U> From<Alpha<T>> for Alpha<U> where U: From<T>` _does_ cause a conflict with `impl<T> From<Alpha<T>> for Alpha<T>` because `T` may be the same as `U`. I could work around it by making specific implementations for each color space, so it's not yet catastrophic. The introduction of generics will be interesting, to say the least.
