### ISSUE TITLE
HSLuv support

### ISSUE THREAD

**Issue by masonium** [Ogeon/palette#112]
[HSLuv](http://www.hsluv.org/) is a more intuitive version of CIELAB Lch, designed for programmatic color generation. I would be happy to attempt an implementation, if you're interested in adding it to `palette`.

**Comment by Ogeon** [comment]
It looks like a useful format, so go ahead! Let me know if you want to discuss anything along the way, or if you change your mind. I'm also usually encouraging opening early pull requests for feedback during the process.

**Comment by Benjamin-L** [comment]
I'm going to try writing up an implementation for this, unless @masonium is still interested/working on it.

**Comment by masonium** [comment]
Somehow I completely missed @Ogeon 's reply :-/, so I never started working on it. @Benjamin-L feel free to take it form me.

**Comment by Ogeon** [comment]
I'm happy with this arrangement if you two are. Feel free to come with feedback too, @masonium, when there's a pull request. It's nice to have more than just my eyes on it.

**Comment by Artoria2e5** [comment]
It's based on CIE LUV, not CIE LAB. Someone has to do the LUV part first.

**Comment by masonium** [comment]
Very late, but I submitted  PR #219 to address this issue.
