### ISSUE TITLE
no_std support is broken

### ISSUE THREAD

**Issue by sajattack** [Ogeon/palette#125]
I tried using this crate in a no_std context and it doesn't work because the inclusion of `num_traits::Float` isn't behind a feature flag, and evidently, the stuff behind the `libm_works` feature flag doesn't "work".

**Comment by Ogeon** [comment]
Thanks for pointing it out! It's supposed to not be broken, if i remember correctly. Can you provide a bit more information to make it easier to reproduce your situation? That would help a lot in figuring out why it stopped working. At least

* which target you are compiling against,
* which `palette` feature set you have enabled,
* and the errors the compiler prints.

A minimal example project would be the best, if possible. It doesn't have to do anything meaningful.

**Comment by sajattack** [comment]
* `thumbv6m-none-eabi`
* `default-features=false`, `named`
* 
```
error[E0432]: unresolved import `num_traits::Float`
  --> /home/paul/.cargo/git/checkouts/palette-3cb107dfe0152157/1342cce/palette/src/float.rs:12:9
   |
12 | pub use num_traits::Float;
   |         ^^^^^^^^^^^^^^^^^ no `Float` in the root. Did you mean to use `float`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `palette`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Ogeon** [comment]
Thanks for the details! I suppose you are using the 2018 edition? Not that I think it makes a difference, but who knows? What you provided should definitely be enough. :+1:

I can't say off the top of my head why this wasn't a problem half a year ago. It seems to have been std only for over a year.

**Comment by sajattack** [comment]
Yes, 2018 edition.
