### ISSUE TITLE
[r, g, b] -> palette::Lch -> shift_hue_by(90.0) -> [r', g', b'] ?

### ISSUE THREAD

**Issue by gamecubate** [Ogeon/palette#128]
How to I convert an RGB triplet to an Lch color, shift its hue by n degrees, then re-output as RGB (triplet)? I've been going over the docs but must have missed something for all attempts  at this, by me, has failed. Thanks in advance.

EDIT:
Reason for this is that my app uses SDL2 extensively, including its Color::RGBA type. No crate exists in a vacuum and I wish palette's README.md examples included one for this or similar.

**Comment by Veykril** [comment]
If I am not misreading your issue then I am fairly certain that the example code your question is actually in the readme [here](https://github.com/Ogeon/palette#color-spaces)?

Written with each function given its own line it would look something like this:
```rust
extern crate palette;
use palette::{Srgb, LinSrgb, Lch, Hue};

let srgb_color = Srgb::new(0.8, 0.2, 0.1);
// convert to Lch
let lch_color = Lch::from(srgb_color);
// shift hue by 180 deg
let shifted_lch_color = lch_color.shift_hue(180.0);
// convert back to Srgb
let shifted_srgb_color = LinSrgb::from(shifted_lch_color);
```

**Comment by gamecubate** [comment]
Spot on. But it's the periphery I am having issues with. i.e., from [u8, u8, u8] and back.

**Comment by Veykril** [comment]
Was about to edit my comment after rereading the issue title. For that you might want to check out the (Pixel)[https://docs.rs/palette/0.4.1/palette/encoding/pixel/trait.Pixel.html] trait, it lets you cast slices into the color and back with the `*_raw` functions from what I can tell.

**Comment by Ogeon** [comment]
Hi @gamecubate! @Veykril got most of it right, but you will have to do some extra conversion to go from u8 to f32 and back. You can use the `Srgb::from_raw` method ([from the Pixel trait](https://docs.rs/palette/0.4.1/palette/encoding/pixel/trait.Pixel.html#method.from_raw)) to go from `[u8; 3]` to `Srgb<u8>`, as mentioned. Then you can use `Srgb::into_format` to go from `Srgb<u8>` to `Srgb<f32>` and continue as usual from there. When going back, you just have to do it all backward, finishing with `Srgb::into_raw`.

**Comment by Ogeon** [comment]
The [hue.rs example file](https://github.com/Ogeon/palette/blob/9577e25e6996c4a9a0c023a6b1bf47fc378c408e/palette/examples/hue.rs) is a bit more fleshed out and should be pretty close to what you are trying to do. That said, I agree that both README.md and the documentation could show the conversion more clearly, since interoperability with other libraries is important. For now, I can say that there is builtin support for conversion to and from slices and arrays up to four elements, as well as using `into_components` and `from_components` on any of the types to convert to and from a tuple.

**Comment by gamecubate** [comment]
Thanks a lot to both of you. I've got more than enough to go on. May post a PR README.md amendment if I can come up with something concrete and useful.

**Comment by Ogeon** [comment]
Great! And that PR would be most welcome. I'm going to close this, as the main question is resolved, but I will open another issue for improving the documentation.
