### ISSUE TITLE
Allow more than just f32 colors

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#13]
I can be useful for some applications to have colors that are based on other numerical types than just `f32`. Most probably for the sake of higher precision or lower memory usage. It would therefore be good to support more than just `f32`, and preferably in a generic way. We can still keep `f32` as the default.

**Comment by Ogeon** [comment]
I know that @sidred was interested in implementing this. Is that still the case?

**Comment by sidred** [comment]
Yeah, I got the basic f32/f64 working.

I am currently trying to implement a Single struct with 2 phantom traits, the color_space and the white point. So you can encode the color_space and the white point with no additional memory

You would have something like Color<Srgb, D65, f32>::new() , Color<Lab, D65,f64> etc. It is taking a bit more work than I expected. i''ll let you know how it goes. If I don't have something by this weekend, I might just implement the struct per color_space version with manual white points. I'll keep you posted.

**Comment by Ogeon** [comment]
Sounds ambitious. I don't know how you are doing it now, but it may be easier if you take it one step at the time. That's why I'm making all these small issues. I expect them to result in one PR each, to keep each problem as isolated as possible. Speaking of which, I'll add an issue for the white point stuff, as well.

Anyway, I'll assign you to this one, and the one about white points, just to make it clear that you are on it. Just let me know if something else comes up.

**Comment by sidred** [comment]
Having some trouble with the macros.

For the make_color macro, I want to map ``` linear_pixel<P: RgbPixel>(pixel: &P);``` to ```linear_pixel<T: Float, P: RgbPixel<T>>(pixel: &P);```. 

But I am having trouble matching the macro syntax.  Do you know a quick match for this pattern?

**Comment by Ogeon** [comment]
Ah, crap. Well, the functions doesn't have to be exactly correct, so can't you get away with simply doing `$($ty_param:ident : $ty_param_trait:ty),*`? Or will it complain about an unknown type `T`?

**Comment by Ogeon** [comment]
Thinking about it, you shouldn't have to map it to `linear_pixel<T: Float, P: RgbPixel<T>>(pixel: &P);`, since `T` should be known from `impl<T: Float> Color<T>`. We may have to give it to the macro, though, to make sure it's the same `T`.

**Comment by sidred** [comment]
using ``` ty_param:ident : $ty_param_trait:ty), ``` gives the error ``` no rules expected for the token >>```

The best I could come up with was ```  <$( $ty_params:ident: $ty_param_traits:ident $( <$( $ty_inner_traits:ident ),*> )* ) ),*>```. But I still get the same error. But in this case atleast ``` linear_pixel<T: Float<U>, P: RgbPixel>``` works. The only difference is the comma after the > symbol.

**Comment by sidred** [comment]
True , we just need ``` linear_pixel<P: RgbPixel<T>>```. But its the two >> symbols thats causing the issue.

**Comment by Ogeon** [comment]
That will do. Alternative syntax is fine as long as it's not too obscure. It can be refined later.

**Comment by sidred** [comment]
I am not sure you understood me. I still don't have a working solution for ``` linear_pixel<P: RgbPixel<T>>```

**Comment by Ogeon** [comment]
Oh, ok. But if it's the `>>` that is tripping it up, then you could either use `[$( $ty_inner_traits:ident ),+]` or something, or maybe require a comma after each type parameter (`<$( $ty_params:ident: $ty_param_traits:ident $( <$( $ty_inner_traits:ident ),*> )* ) ,)*>` see the last `,`?).

**Comment by Ogeon** [comment]
Or is the problem in the expanded code?

**Comment by sidred** [comment]
Here is a minimized example

```
macro_rules! make_color {
    (
        $(
            $ctor_name:ident $( <$( $ty_params:ident: $ty_param_traits:ident $( <$( $ty_inner_traits:ident ),*> )*),*> )* ($($ctor_field:ident : $ctor_ty:ty),*);
        )+
    ) => (
        $(
             pub fn $ctor_name$(<$($ty_params : $ty_param_traits),*>)*($($ctor_field: $ctor_ty),*) -> Color {}
        )+
    )
}

make_color! {
                 linear_rgba8(red: u8, green: u8, blue: u8, alpha: u8);
                 linear_pixel<T: Float>(pixel: &P);
                //  linear_pixel<T: Float,P: RgbPixel<T>>(pixel: &P);
}
```

This is my solution without moving the comma.  ```<T: Float>``` works.  
However, neither ``` <T: Float<U>>``` nor ```<T: Float,P: RgbPixel<T>>``` work, with the error  ```no rules expected the token >> ```.


Your 2 solution don't work with  ```<T: Float>```

This is driving me crazy!!!

**Comment by Ogeon** [comment]
A simple non-robust workaround: replace `>>` with `> >`. Then it won't be interpreted as shifting.

**Comment by sidred** [comment]
Thanks

**Comment by sidred** [comment]
Having an issue with the into trait for hues: 

```
impl<T: Float> Into<T> for LabHue<T> {
    fn into(self) -> T {
        normalize_angle(self.0)
    }
}
```

This errors with the message ``` conflicting implementations of trait `core::convert::Into<_>` for type `hues::LabHue<_>````. This works for the concrete type f32 though.

Following [this](https://users.rust-lang.org/t/cant-see-conflicting-trait-implementation/2796) thread, maybe just implement the to_owned trait? Not sure what the best way is.

**Comment by sidred** [comment]
Implied a  ```to_float(&self) -> T``` on the LabHue and using it in place of into()

**Comment by Ogeon** [comment]
`to_owned` is semantically strange. We haven't borrowed anything. The conflict with `Into` is that `T` could be `LabHue<T>`, so it conflicts with `impl<T> Into<T> for T {`. We could implement `Into` for `f32` and `f64`, as well as keeping the `to_float` method you added. That would probably cover almost all of the use cases, anyway. The same goes for `From`.

**Comment by sidred** [comment]
For the Rgb Color

```
impl<T: Float> RgbPixel<T> for (T, T, T, T) {
    fn from_rgba(red: T, green: T, blue: T, alpha: T) -> (T, T, T, T) {
        (red, green, blue, alpha)
    }

    fn to_rgba(&self) -> (T, T, T, T) {
        self.clone()
    }
}
```

is causing an error ``` conflicting implementations of trait `rgb::RgbPixel<u8>` for type (u8, u8, u8, u8)``` when the u8 implementation is defined.

```
impl<T: Float> RgbPixel<T> for (u8, u8, u8, u8) {
    fn from_rgba(red: T, green: T, blue: T, alpha: T) -> (u8, u8, u8, u8) {
        ((red * T::from(255.0).unwrap()) as u8,
         (green * T::from(255.0).unwrap()) as u8,
         (blue * T::from(255.0).unwrap()) as u8,
         (alpha * T::from(255.0).unwrap()) as u8)
    }
```
Any ideas?

This is the final issue that's blocking the float trait implementation.  When I comment out the above implementation all the tests pass, but the examples don't compile.

**Comment by Ogeon** [comment]
We could just leave them to be explicit for now. Those parts will change later, with #7, so we can revisit that part then. What's the problem with the examples?

**Comment by sidred** [comment]
Most of the examples use the impl for u8 to create the rgbpixel variables.  Let me see if I can find a quick workaround.

**Comment by Ogeon** [comment]
What does the error messages say? Did you set `f32` as the default?

**Comment by sidred** [comment]
I can just implement the ```impl<T: Float> RgbPixel<T> for (T, T, T, T)``` separately for f32 and f64. Should work for now.

**Comment by Ogeon** [comment]
That's what I meant. :smile: Keep them as close to `impl<T: Float> RgbPixel<T> for (f32, f32, f32, f32)` (and the same for `f64`) as possible for now. We can bother with those later.
