### ISSUE TITLE
Mark `new` functions as `const`

### ISSUE THREAD

**Issue by kgv** [Ogeon/palette#134]
It allows:
`const COLOR: Srgba = Srgba::new(1.0, 1.0, 1.0, 1.0);`

**Comment by Ogeon** [comment]
Yep, that's a good idea! It should be possible for most, if not all of them. I don't think any of them use float arithmetic, which wasn't stable yet in const, last time I checked.

**Comment by Ogeon** [comment]
Turns out this has to wait for trait bounds other than `Sized` to be stabilized for `const` functions.
