### ISSUE TITLE
Packed formats

### ISSUE THREAD

**Issue by Diggsey** [Ogeon/palette#144]
It's common to store sRGB values packed in a `u32` (eg. 0xAARRGGBB) - it would be helpful to provide functions to convert to this format.

I need to convert from linear, floating-point RGB to a packed sRGB u32, and the way I'm currently doing it is like this:
```rust
fn to_srgb(color: Vector3<f64>) -> u32 {
    let src = LinSrgb::new(color[0], color[1], color[2]);
    let dst: Srgb<u8> = Srgb::from_format(Srgb::from_linear(src));
    0xFF000000 | ((dst.red as u32) << 16) | ((dst.green as u32) << 8) | (dst.blue as u32)
}
```

I'm not sure if this is the best way to do it.

**Comment by Ogeon** [comment]
That would probably be a nice addition, but the implementation would have to be clear about what the channel order is. 🤔 Some put the alpha in one end, and some in the other. Some reverse the red, green and blue, and so on. The assumed channel order in Palette is currently RGBA and there is not yet any built-in way of encoding them in any other order, so being able to do it would be a new addition.

Your example function is about as good as it gets with the current API. It's possible to make changes like replacing `from_format` with `.into_format()` and such, but it's still the same procedure in the end. 🙂
