### ISSUE TITLE
impl std::iter::DoubleEndedIterator for palette::gradient::Take

### ISSUE THREAD

**Issue by jansegre** [Ogeon/palette#153]
Would allow doing `gradient.take(n).rev()` without collecting. My main reasoning for that is basically because for lower values of `n` (1 or 2), `gradient.take(n)` is a bit skewed to the first colors of the gradient.

**Comment by Ogeon** [comment]
Makes sense to me. I see no reason why it wouldn't be double ended.

As for the skewing, I suspect there may have been a mistake when it was implemented and that the last stop is not at the very end of the gradient. That should be fixed.
