### ISSUE TITLE
Forgot default white point in alpha type aliases

### ISSUE THREAD

**Issue by piegamesde** [Ogeon/palette#177]
`Lch` is a valid type, but `Lcha` is not. I have to specify the white point with `Lcha<white_point::D65>`. In the type alias definition, `type Lcha<Wp, T = f32> = Alpha<Lch<Wp, T>, T>;` should be changed to `type Lcha<Wp = D65, T = f32> = Alpha<Lch<Wp, T>, T>;` to remove that inconsistency.

I haven't checked all color types, but at least the `Laba` type suffers from this as well.

**Comment by Ogeon** [comment]
Thanks for pointing this out!

I don't remember if there was a reason for doing it that way or if it was an just oversight. Most likely a mistake or some reasoning that it would be inherited from whatever other color space is used. That last part is probably more inconvenient than helpful.
