### ISSUE TITLE
Continuous benching action

### ISSUE THREAD

**Issue by okaneco** [Ogeon/palette#180]
As discussed in #95, the available github actions seem to be
- https://github.com/rhysd/github-action-benchmark
- https://github.com/matchai/criterion-compare-action

continuous-benchmark only supports the unstable `cargo bench` at this time, not criterion. criterion-compare-action posts comments on the commit, not inside the PR. Since it's the only one that works for our needs, criterion-compare-action is probably worth experimenting with.

Caveat, Github Actions may be pointless for benching if they don't have consistent machines they use to execute.

**Comment by CryZe** [comment]
cargo bench is not unstable. You use cargo bench with criterion.

**Comment by okaneco** [comment]
Thanks for the clarification, I didn't mean to imply cargo bench was unstable. I didn't know the bencher was unstable until recently because I'd only been using criterion.

**Comment by Ogeon** [comment]
I didn't find any interesting alternatives either, when I looked, so I will give criterion-compare-action a try. I looks like they fixed the commenting without closing the issue, so it may be just fine. I think it's exactly what I'm after at the moment. The other one can be added later, for the fun of having the historical graphs.
