### ISSUE TITLE
Add and Substract - clamp after operations?

### ISSUE THREAD

**Issue by sidred** [Ogeon/palette#19]
For colors with known ranges like rgb, hsl etc., should we clamp the values? A possible issue is with the f32 -> u8 conversion panicking if not clamped.

**Comment by Ogeon** [comment]
That may mess with the math. I think it's better to clamp just before converting. Isn't that already implemented?

**Comment by sidred** [comment]
Currently there is no clamping. 
```
impl<T: Float> Add<Rgb<T>> for Rgb<T> {
    type Output = Rgb<T>;

    fn add(self, other: Rgb<T>) -> Rgb<T> {
        Rgb {
            red: self.red + other.red,
            green: self.green + other.green,
            blue: self.blue + other.blue,
            alpha: self.alpha + other.alpha,
        }
    }
}
```

**Comment by sidred** [comment]
Currently not implemented 

```
impl<T: Float> RgbPixel<T> for (u8, u8, u8, u8) {
    fn from_rgba(red: T, green: T, blue: T, alpha: T) -> (u8, u8, u8, u8) {
        ((red * T::from(255.0).unwrap()).to_u8().unwrap(),
         (green * T::from(255.0).unwrap()).to_u8().unwrap(),
         (blue * T::from(255.0).unwrap()).to_u8().unwrap(),
         (alpha * T::from(255.0).unwrap()).to_u8().unwrap())
    }

    fn to_rgba(&self) -> (T, T, T, T) {
        let (r, g, b, a) = *self;
        (T::from(r).unwrap() / T::from(255.0).unwrap(),
         T::from(g).unwrap() / T::from(255.0).unwrap(),
         T::from(b).unwrap() / T::from(255.0).unwrap(),
         T::from(a).unwrap() / T::from(255.0).unwrap())
    }
}
```

**Comment by Ogeon** [comment]
[Yes, it is](https://github.com/Ogeon/palette/blob/f1cb89b0c71d8b321d4fb2d5f3d4348ee660685b/src/rgb.rs#L194) in each conversion function.

**Comment by sidred** [comment]
I've at this looked at this function [link](https://github.com/Ogeon/palette/blob/f1cb89b0c71d8b321d4fb2d5f3d4348ee660685b/src/rgb.rs#L577)

I am not sure I understand it correctly. Lets say I have 2 Rgb<f32> and I add them and convert to [u8;3]. These is no clamping in this process, is there?

**Comment by Ogeon** [comment]
No, it happens in those functions I linked to, just before those are called. It may still be a good idea to clamp after multiplying with 255, because of how floating point math works.
