### ISSUE TITLE
Oklab color space

### ISSUE THREAD

**Issue by Veykril** [Ogeon/palette#201]
Looks like a new interesting color space appeared recently called Oklab, https://bottosson.github.io/posts/oklab/. I assume this would potentially make a nice addition to `palette`'s supported color spaces.
Another blog post going into the details from another point of view is here https://raphlinus.github.io/color/2021/01/18/oklab-critique.html.

**Comment by Ogeon** [comment]
Hi! Thanks for posting this and that second link is particularly interesting. I'll have to study it more later! Critique aside, Oklab seem to have useful properties and it's already being implemented in a pull request. It probably shouldn't be seen as scientifically proven in any way (not to say it's completely arbitrary either), but rather an opinionated tool for certain use cases.

**Comment by Veykril** [comment]
Ah my bad, I only checked the issues but forgot to check the pull requests for whether it got already brought up here 😄

**Comment by Ogeon** [comment]
Don't worry about it! And you brought some good reading material to the discussion. 😁
