### ISSUE TITLE
Conversion between colors with ::from not implemented if local crate is used

### ISSUE THREAD

**Issue by NicolasKlenert** [Ogeon/palette#204]
I found an odd behaviour while trying to use a fork of this library.

As an example, conversion like this `Hsv::from(LinSrgb::new(1.0, 0.1, 0.1))` are working fine when using palette as an extern crate. But if I want to use a fork (by using `palette = {path = "../palette/palette"}` instead of `palette = "0.5"`) then I get the error that the trait From wouldn't be implemented.

Any idea why this would happen? The fork also has version 0.5.0 and was not changed at all.

**Comment by Ogeon** [comment]
Hi! If you are comparing to the version on crates.io, that error is expected. The version here has had the `From` and `Into` implementations replaced with `FromColor` and `IntoColor` with slightly different semantics. So just replace `from` with `from_color`, import the trait, and you should be good to go.

**Comment by NicolasKlenert** [comment]
Thanks, this explains a lot! I wasn't aware of the difference since the version numbers were the same.

For anyone else wondering about this, [here](https://github.com/Ogeon/palette/pull/176) is the pull merge with the breaking changes and description. The traits themselves also explain the difference between `From/Into` and `FromColor/IntoColor`.

**Comment by Ogeon** [comment]
Ah, yes. I prefer to increment the version as part of the release preparations. Just so nobody else have to think about it. But the repo is also almost always a work in progress.

Any way, good to see that it solved your issue. Enjoy the preview and let me know if you run into more trouble!
