### ISSUE TITLE
Update benchmarks on pull requests

### ISSUE THREAD

**Issue by NicolasKlenert** [Ogeon/palette#208]
At the moment the benchmarks which are done automatically at every PR are always failing. This should not be the case if the `criterion-compare-action` is updated (there is a [new repo](https://github.com/boa-dev/criterion-compare-action), because matchai stopped working on it).

**Comment by Ogeon** [comment]
Nice, I hadn't seen the updated version. I was considering making it only print the results in the log, but updating it looks like a better option now! Thanks for pointing it out!
