### ISSUE TITLE
Avoid equality tests in examples, and use approx otherwise

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#21]
Floating point numbers are crazy and should not be trusted. They should therefore not be compared in the examples (for aesthetic reasons) and any unit test that compares them should make use of the `approx` crate.

**Comment by sidred** [comment]
Should be closed by #51

**Comment by Ogeon** [comment]
There are still some examples where regular equality is used (https://ogeon.github.io/docs/palette/master/palette/trait.GetHue.html for example), so this issue stays as a reminder until all of those have been changed.
