### ISSUE TITLE
Removing mod.rs files?

### ISSUE THREAD

**Issue by okaneco** [Ogeon/palette#212]
This is more of a housekeeping issue, but would a PR be welcome that removes `mod.rs` files in the `src` folder? They're not needed in Rust 2018 edition and can be confusing when several files are open in an editor that all have the same name. The integration tests would stay the same but `/src/alpha/mod.rs` and friends would change to `/src/alpha.rs` etc.

```bash
$ find . -name 'mod.rs'
./src/alpha/mod.rs
./src/blend/mod.rs
./src/encoding/mod.rs
./src/encoding/pixel/mod.rs
./src/gradient/mod.rs
./src/luma/mod.rs
./src/random_sampling/mod.rs
./src/rgb/mod.rs
./tests/color_checker_data/mod.rs
./tests/convert/mod.rs
./tests/pointer_dataset/mod.rs
```
After
```bash
#       renamed:    src/alpha/mod.rs -> src/alpha.rs
#       renamed:    src/blend/mod.rs -> src/blend.rs
#       renamed:    src/encoding/mod.rs -> src/encoding.rs
#       renamed:    src/encoding/pixel/mod.rs -> src/encoding/pixel.rs
#       renamed:    src/gradient/mod.rs -> src/gradient.rs
#       renamed:    src/luma/mod.rs -> src/luma.rs
#       renamed:    src/random_sampling/mod.rs -> src/random_sampling.rs
#       renamed:    src/rgb/mod.rs -> src/rgb.rs

```

**Comment by Ogeon** [comment]
Good question. I can be a bit old school, so I'm simply more used to having `mod.rs` files. I think a point in their favor is that they collect everything related to the module under the same folder, but that would be more circumstantial. Like good for renaming a module, but how often does that happen? Being able to tell the difference between them without relying on whether the editor adds the directory or not is more of an everyday benefit. And I better get with the times, so I would say go ahead! What's most important for me is that it's consistently one or the other.

**Comment by okaneco** [comment]
3 years is still pretty new :slightly_smiling_face: 

I agree about the consistency and the pros/cons. I used `mod.rs` out of habit but after using the new way enough, I've grown to prefer it. I never felt the need to change it before because it seemed like unnecessary churn, but 8 files in the main library seemed like a tipping point when I had a few tabs open for files even with directories in the name.

I had a paragraph in the first post initially explaining about integration tests but removed it. In order to remove the mods there, we'd have to move them all to one crate/folder with a `main.rs` file (`fn main()` gets inserted automatically and you put the `mod`s in there) since each test compiles to its own binary. Because the integration tests are so small, the gains aren't really noticeable. I learned more about how integration tests are compiled from this blog and went a bit down a rabbit hole on it. Luckily, my projects are too small to have to worry about those problems.  
https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html

**Comment by Ogeon** [comment]
3 years is still long enough for a lot of people to learn the new structure. It's what they are teaching in the book (I had to look it up out of curiosity), so us oldtimers will eventually be a minority if we aren't already. :laughing: I'm happy to adapt! I just didn't think too much about it.

I think it's fine to wait with the integration tests. They may need their own cleanup pass, but thanks for looking into it and linking that post!
