### ISSUE TITLE
Printing Color in the Terminal for Inspection and Debugging

### ISSUE THREAD

**Issue by NicolasKlenert** [Ogeon/palette#234]
As a quality of life improvment, I would like to suggest printing a colored block alongside any (debug) information of a color.
As this is a library and not an executable, it doesn't have to be anything fancy. I was thinking about using the ascii character █ and coloring it with the help of a crate. 

A crate which seemed fine for this purpose is the [colored](https://github.com/mackwic/colored) crate with its `.truecolor()` method on strings.

**Comment by Ogeon** [comment]
It would indeed be a neat feature and useful for debugging sometimes! However, I think it would fit better as an extension library than included in Palette itself. First, it would have to be optional, to keep the library as slim as possible, to not enforce it on everyone, and especially if it can't be done without requiring `std` to be enabled. It would also have to be done in a way that is as cross platform as possible. I bet colored has that figured out, but the feature of showing any color is itself still not universal and may need to be disabled on some outputs (logging to file, for example).

All in all, even looking past the usual maintenance, complexity, and a wider scope, I think it's a bit too subjective (like how and when to print it) and circumstantial (it's only really doing anything in debug prints) to weigh up the "cost" of including it. I'm afraid I have to make the judgement call to not include it, despite being a nice feature and something that clearly can be useful.

Making it a separate library gives it the freedom to be as opinionated as it need to and have its own goals and "platform support". I think that would benefit the feature more and with little to no downsides, compared to being built in.

**Comment by NicolasKlenert** [comment]
Thank you for the consideration and for explaining your reasoning for not including it. I do see the problems you pointed out and I understand your decision.
By the way, kudos to you for answering so quickly and being such an active crate maintainer in general!

**Comment by Ogeon** [comment]
Thanks! It's a fun library to maintain and I have a lot of ideas for how I want to improve it. 😁 It can just sometimes be a bit difficult for me to sit down and actually write the code on my free time when programming is also my day job. 😅 But answering questions and checking pull requests is at least relatively fast and simple to schedule, so it's much easier to find some time for that and still be able to do other things!
