### ISSUE TITLE
make palette_derive optional

### ISSUE THREAD

**Issue by gilescope** [Ogeon/palette#285]
palette_derive gets pulled in even with default-features = false.
Less deps is more if it's possible?

**Comment by Ogeon** [comment]
The derive crate is currently primarily used for implementing most of the conversions between the colors. It's _a lot_ of boilerplate and tricky to do with a regular macro. The other derives are easier to also implement in other ways, so conversion is the main reason. If it were to be disabled without replacement, you would have to look through the documentation for all the steps to convert between color spaces.

I'm at least definitely open for making it more lean, if nothing else! It's not that I don't care about dependencies and build time, I'm just not a fan of the alternatives I have seen so far. The best would be if specialization can be added to the language in a way that solves it. Not sure if it actually will.

**Comment by gilescope** [comment]
Ah sorry, I thought the derive was more of a bolt on. If it’s pivotal then
best close this!

**Comment by Ogeon** [comment]
Oh, no worries! Thanks for bringing this up, it's better to ask than to keep on wondering. 😁

**Comment by Ogeon** [comment]
I decided to do some dependency shaving in #286. Got rid of some of the more low hanging fruit. There's still more that could be done (maybe even replace `syn` in the future), but I'll close this for now.

**Comment by gilescope** [comment]
Thank you! 30% less energy used all helps on the climate change front as
well as being faster.

**Comment by Ogeon** [comment]
I'm assuming it's a best case but still something!
