### ISSUE TITLE
Add EuclideanDistance trait

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#288]
### Discussed in https://github.com/Ogeon/palette/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **okaneco** March  6, 2022</sup>
I find myself rewriting boilerplate often enough that maybe it'd be nice to have upstream. The `ColorDifference` trait exists but I don't always need the expensive CIEDE2000 calculation. Sometimes I'd like a more simple Euclidean distance/norm or the squared distance for comparing to a tolerance value.

This is a sketch of what I had in mind.
```rust
fn distance_squared(&self, other: &Self) -> T {
    (self.red - other.red).powi(2)
        + (self.green - other.green).powi(2)
        + (self.blue - other.blue).powi(2)
}

fn distance(&self, other: &Self) -> T {
    ((self.red - other.red).powi(2)
        + (self.green - other.green).powi(2)
        + (self.blue - other.blue).powi(2))
    .sqrt()
}
```

Perhaps this can be added to the `ColorDifference` trait?

There may be other "general enough" functions that people find themselves re-implementing similar to these which would carry their weight as additions to the library.</div>

**Comment by Ogeon** [comment]
Thanks a lot for giving this a try! I think it makes sense to simply skip anything with polar coordinates. At least for `Hsv`, `Hsl` and `Hwb` that map weirdly to `Rgb`. I prefer to draw the line where it becomes subjective or stops being well defined. I have had a though of making Cartesian versions of them too, since it's useful for interpolating nicely, and those could implement this trait. I have nothing concrete in mind but maybe something like `Cartesian<PolarColorType, Shape>` or `CartesianHsv<Shape>` (etc.) that allows it to be interpreted as cylindrical, conical or bi-conical.

Some of the other spaces do have clear Cartesian counterparts (`Lch` and `Lab` are 1:1 the same space in that sense) and could be converted. Maybe that's fine after all, since it will behave in a much more expected way than those who don't map 1:1 to anything.

**Comment by Ogeon** [comment]
I'm implementing this as part of some general color difference improvements in #316. Let me know if there's anything I missed that you were about to add.

**Comment by okaneco** [comment]
Thanks so much for working on this, looks great. I think that covers most use cases I had in mind.

Since then, I came across this paper where the HyAB color distance metric is presented in Equation 3 on page 4. It seems like it could be a good addition to `Lab` because it separates the effect of luma and chroma/hue in color difference calculation.
http://markfairchild.org/PDFs/PAP40.pdf

**Comment by Ogeon** [comment]
Interesting! It looks like HyAB would be a simple and good addition. I'll skip it in the current PR, though, just to not rush it in. Would you like to open an issue for it? Otherwise, I'll do it and link to your comment. :slightly_smiling_face:
