### ISSUE TITLE
Blending

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#3]
There should be support for the common blending functions, like add, subtract, screen, overlay, etc. This may be restricted to RGB, unless it's intuitive in other spaces as well.

**Comment by retep998** [comment]
I don't know of any color spaces other than linear RGB that guarantee being able to trivially blend colors and get the correct result.

**Comment by Ogeon** [comment]
Yeah, I think so too. This will most likely end up being an `Rgb` and `Color` exclusive feature.
