### ISSUE TITLE
Pixel to Struct of Arrays (and back again!)

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#305]
## Description

As discussed in https://github.com/Ogeon/palette/discussions/303, it would be useful to have an interface for converting an array/`Vec` of colors to and from Struct of Arrays format. The first step should be:

- [x] Construction of `Rgb<S, Vec<T>>` from some `I: IntoIterator<Item = Rgb<S, T>>`, and the same for the other color types.
- [x] Make it possible to get a color at some index. For example `fn get_mut(&mut self, index: usize) -> Option<Rgb<S, &mut T>>`.
- [x] Make it possible to iterate over the colors. For example `fn iter_mut(&mut self) -> impl Iterator<Item = Rgb<S, &mut T>`.
- [x] Make it simple to read from and assign to colors with reference components, such as `Rgb<S, &mut T>`.
- [x] Add counterparts to  `Vec::clear` and `Vec::extend`.
- [x] Make it possible to push and pop individual colors.

In addition to that, we may want to add chunks and windows iterators.

The reference components will likely be necessary, due to the split into separate arrays, unless there's a smarter solution. They don't have to enable much more than reading and writing, though. It's also what would make it hard to implement the `Index` and `IndexMut` traits, if possible at all.

## Motivation

The discussions in https://github.com/Ogeon/palette/discussions/303 covers it pretty well. One of the main reasons for a built-in interface is that it gives a way to correctly preserve the color type information across conversions. It also lowers the bar for working with SoA data.

**Comment by okaneco** [comment]
Good summary :slightly_smiling_face: 

Another feature that I think would be useful is some way to reuse the existing allocations. It might be an `extend`-like interface so that users could call `clear` on the existing data and re-initialize with an iterator.

**Comment by Ogeon** [comment]
Ah, yes, that should also be there! I'll edit the description to include them...
