### ISSUE TITLE
Add support for HWB color model

### ISSUE THREAD

**Issue by johansigfrids** [Ogeon/palette#32]
I was reading through the CSS level 4 color module to see what's coming up and came across a new color model: [HWB](https://drafts.csswg.org/css-color-4/#the-hwb-notation). It was a total love at first sight. It works allowing you to select a hue and then mix in whiteness and blackness. 

Support for it in this library would be great.

**Comment by Ogeon** [comment]
Huh! Looks like it's already quite common, since it's used in the triangle color wheel, and the future inclusion in CSS makes this even more interesting. The implementation looks simple enough, so I'll schedule it for 0.2.1.
