### ISSUE TITLE
crate lacks test assets

### ISSUE THREAD

**Issue by jonassmedegaard** [Ogeon/palette#365]
Tests fail when run from generated crate (not from git source).

Including test assets with the crate makes those tests succeed, like this:
```patch
--- a/palette/Cargo.toml
+++ b/palette/Cargo.toml
@@ -6,7 +6,6 @@
     "scripts/*",
     "examples/*",
     "tests/*",
-    "regression_tests/*",
     "benches/*",
     "res/*",
     ".travis.yml",
```

**Comment by Ogeon** [comment]
This test case has been moved out of the main crate, so a new release will exclude the test. This is good to keep in mind if they are to be re-combined again later.

**Comment by Ogeon** [comment]
I'll close this for now, since the next release shouldn't have this issue, but feel free to re-open it if I misunderstood the situation.
