### ISSUE TITLE
Color profile support

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#37]
Add some sort of support for [ICC profiles](https://en.wikipedia.org/wiki/ICC_profile). Could be statically embedded, fully dynamic or both. This will make things like accurate CMYK possible, as discussed in #6.

**Comment by Ogeon** [comment]
Here is a pdf with the reference: http://www.color.org/specification/ICC1v43_2010-12.pdf

**Comment by sidred** [comment]
The document talks about  media-relative colorimetric data  and ICC-absolute colorimetric data for XYZ. Can we assume that the media-relative is similar to White Point or separate the XYZ by the ICC or media trait?

**Comment by Ogeon** [comment]
I don't know. I haven't studied it enough.

**Comment by Ogeon** [comment]
ICC profiles are complex enough on their own and there are other crates for it. I prefer making interoperability with those work smoothly.
