### ISSUE TITLE
Color Enum with Rgb Variants and White Point changes

### ISSUE THREAD

**Issue by sidred** [Ogeon/palette#40]
How to handle color macro with rgb variant and white point changes?

Currently
```
enum Color<T:Float> {
  Lab(Lab<T>),
  Rgb(Rgb<T>),
  Hsl(Hsl<T>),
  Xyz(Xyz<T>),
 .. etc
}
```
With proposed changes it becomes

```
enum Color<RGB: RgbVariant, WP:WhitePoint, T:Float> {
  Lab(Lab<WP, T>),
  Rgb(Rgb<RGB, WP,T>),
  Hsl(Hsl<V, WP, T>),
  Xyz(Xyz<T>),
 .. etc
}
```

So for example for Color::Xyz, we will still have to specify the RgbType and WP even though we do not use it. Is there any alternative?

**Comment by Ogeon** [comment]
There is no alternative if we want to keep the `Color` type and make it generic over white point and RGB variant/primaries.
