### ISSUE TITLE
Get a named color from a color value

### ISSUE THREAD

**Issue by Princesseuh** [Ogeon/palette#421]
## Description

Hello! Love this library, makes it very convenient to work with colors.

The ability to get a RGB value from a named color is amazing, but I've found myself wanting the reverse: I have a color (in my case, `Srgba<f32>`, but I assume the same could apply for other formats and types) and would like to get the named equivalent if it exists. If `COLORS` was exported, it would be trivial to go through the values to find that, but unfortunately it is not exposed.

## Motivation

My precise use case is transforming colors into the corresponding CSS, including a named color if it exists.

**Comment by Ogeon** [comment]
Hi, thanks for the suggestion! It would make sense to expose an iterator with names and values, that could be searched.

**Comment by Princesseuh** [comment]
@Ogeon Will this change be published to crates.io? No pressure intended!

**Comment by Ogeon** [comment]
Yes, eventually. There are a couple of tings I would like to have done first, but I haven't had a lot of time/energy recently and will be busy during the coming weeks. Holidays and stuff. I should try to wrap up a release after that.
