### ISSUE TITLE
Lab and Lch values

### ISSUE THREAD

**Issue by sidred** [Ogeon/palette#49]
Continuing discussion from #48.

Lab values are currently scaled, L by 100 and a and b by 128. Even though a and b are unbound, typical ranges are -128 to 128. 

By my limited research so far, I have not seen scaled lab values used ( unlike rgb which is usually assumed in the range 0-1 ). For example Conversion formula's, Color Difference formula's and most research papers assume unscaled lab values (I am happy to be corrected on this). 

Right now using the lab spaces implies unnecessary scaling when used practically. So I am proposing that the Lab values should be changed to be unscaled. Same for Lch values.

If the decision is to still scale the value, we should provide a new_from_unscaled and into_unscaled function, to get values in and out.

**Comment by Ogeon** [comment]
> Color Difference formula's and most research papers assume unscaled lab values

I don't know why, but I didn't even think about that. The current scaling turns out to be even worse than I thought. This is probably one of those times when it's better to not be so clever.

**Comment by sidred** [comment]
Remember to change the default precision for Lab and Lch when scaling is removed if necessary.

**Comment by sidred** [comment]
With the blending additions, I am not sure whether storing the unscaled or scaled is better. Need to figure out if the blending or conversions are the more common operations.

**Comment by Ogeon** [comment]
Blending isn't implemented for `Lab` and `Lch` (so far only `Rgb`, `Luma` and `Color` + alpha wrappers). I'm not sure if it makes any sense at all for the other types.
