### ISSUE TITLE
Equal Trait

### ISSUE THREAD

**Issue by sidred** [Ogeon/palette#50]
Should partial equality be customized for each color to be within a tolerance level? Or maybe have a separate ColorEqual trait. 

It will be better than the current macro which cannot take hues into account and it will definitely help in the tests. 

I am not sure about its use case other than the tests. Another issue is selecting the right tolerance level.

**Comment by Ogeon** [comment]
The approx crate has a [special equality trait](http://bjz.github.io/approx/approx/trait.ApproxEq.html) for this. I didn't implement it straight away because I wasn't sure if it would be necessary or if I would use it at all. It has the tolerance level and everything.

**Comment by sidred** [comment]
But do you see any use case for this other than the tests?

**Comment by Ogeon** [comment]
Sure, other people's tests. Floats are clearly a pain to compare, so this can be useful for more than just tests. Just comparing an input color to a known one is a good example.

**Comment by sidred** [comment]
:)

**Comment by sidred** [comment]
Using the approx eq trait how would you separate the precision for Hues and floats. Example  Hsl, h is from 0-360 and s, l are 0-1. Do you assume the same precision for both or will it be better to provide separate precision like 0.01 for Hue and  0.0001 for the floats?

**Comment by Ogeon** [comment]
We'll unfortunately have to do that. I think that's what the ULPs are about, though. It's a bit unclear, really, but I believe that's the case. The implementation for the hues will be tricky. It may be necessary to take the difference and compare it to 0.0, to compensate for eventual wrap-around at the 180 degrees mark.

**Comment by Ogeon** [comment]
Closed through #51.
