### ISSUE TITLE
Add convenience gradients

### ISSUE THREAD

**Issue by awelkie** [Ogeon/palette#62]
Just like you have named colors, it would be nice to have a collection of predefined gradients.

For reference:
http://matplotlib.org/xkcd/examples/color/colormaps_reference.html
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py

**Comment by Ogeon** [comment]
Sure, why not? Some of those are pretty standard, so I guess they will go well with the color constants. Thanks for the idea :+1:

**Comment by Ogeon** [comment]
Removed the "easy" tag because I underestimated the possibly required amount of Rust knowledge and complexity of the task. It's probably not a super hard problem, just not something that fulfills the criteria of the label.
