### ISSUE TITLE
HSL in sRGB space

### ISSUE THREAD

**Issue by clarcharr** [Ogeon/palette#66]
I may be reading things wrong in the specs, but I believe that the version of HSL that CSS supports is in fact HSL in sRGB space, not linear HSL.

It'd be nice if we had an option to store this type of HSL without hackishly converting an `Hsl` to an `Rgb` and then copying the components from the `Rgb` into an `Srgb`. Again, if I'm wrong and this is actually linear `Hsl`, feel free to ignore this use case.

**Comment by Ogeon** [comment]
Yes, this was something we noticed and was about to change. See #60, where I started implementing support for multiple RGB standards. I haven't checked in what state it is, yet, but it's possible that it can be patched up and merged within a reasonable time... I'll check the comments and see what we got stuck on.

**Comment by Ogeon** [comment]
Hmm. It may have been a difference in our understanding of color primaries, which may mean that the code itself is OK (unless that part is wrong). I'll see if I can look at it tomorrow, and see how complete it is.
