### ISSUE TITLE
Support for serde (de)serialization of color types

### ISSUE THREAD

**Issue by mitchmindtree** [Ogeon/palette#83]
I'm currently using `palette` in a downstream crate where I'd like to allow the user to serialize and deserialize custom `Theme`s - a set of styling defaults including some color types from palette. I'm hoping to avoid writing custom implementations of the serde traits in favour of adding the necessary `derive`s to palette itself where others may also find this useful. Perhaps this could be added as an opt-in feature similarly to [cgmath](https://github.com/brendanzab/cgmath/blob/master/Cargo.toml#L28), [petgraph](https://github.com/bluss/petgraph/blob/master/Cargo.toml#L44) and others do?

**Comment by Ogeon** [comment]
Yes, absolutely! It should probably be quite straight forward to add and
doing it behind a feature sounds like a good plan.

Den tors 15 mars 2018 10:13mitchmindtree <notifications@github.com> skrev:

**Comment by Ogeon** [comment]
I'm adding this in #90. It will be just straight (de)serialization without anything too fancy. The only exceptions are the alpha types that will be flattened, so a JSON serialization of RGB with transparency will be `{"red":0.1,"green":0.2,"blue":0.3,"alpha":0.4}`.

Let me know if any of this doesn't work with your use case and maybe we can tweak it a bit. If you need other field names or a non-struct format, I would recommend creating a custom types for those representations and convert to and from palette types.

**Comment by Ogeon** [comment]
To clarify: it's fine to reopen or continue the conversation even after it's merged. :slightly_smiling_face:
