### ISSUE TITLE
Implement the assign operators for color, alpha and hue types

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#94]
Implement [`AddAssign`](https://doc.rust-lang.org/std/ops/trait.AddAssign.html), [`SubAssign`](https://doc.rust-lang.org/std/ops/trait.SubAssign.html), [`MulAssign`](https://doc.rust-lang.org/std/ops/trait.MulAssign.html), [`DivAssign`](https://doc.rust-lang.org/std/ops/trait.DivAssign.html) for the color types, alpha types and hue types. It may be possible to either base them on the current arithmetic operators or base the current ones on the assign operators. All the colors are `Copy`, so I don't know if it matters which way it is.

**Comment by Veykril** [comment]
I'm currently working on this and noticed that all the arithmetic is only implemented on the Linear Transfer Fn, is it only possible to do standard arithmetic on these or are the others just not implemented yet?

**Comment by Veykril** [comment]
Ah yes, that makes sense then okay. On another note, I wont implement the assign ops by basing them on the non assign ones cause that would force a generic constraint of the non-assign op on the T: Component part, if you can follow me, which in theory should work if I were to do this but it doesnt look that great in my opinion(Same applies the other way around ofc).

**Comment by Ogeon** [comment]
It was just a suggestion, based on a guess. Considering that one implies the other, it kind of makes sense, but it's an unnecessary constraint as you said. Go with your plan! :+1:
