### ISSUE TITLE
Add benchmarks to have a baseline and be able to track improvements

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/palette#95]
There is currently nothing that shows if there are any improvements or regressions between changes. If criterion is used, we may be able to set up something like https://github.com/matchai/criterion-compare-action (or if there are better alternatives) to visualize how each pull request affects the numbers.

Suggestions for what's worth measuring are welcome!

**Comment by Veykril** [comment]
I'll try my hands at this with criterion to get an understanding of how to use it. Just did a simple one already with LinSrgb and the difference between the color addition and a 3-float tuple addition is non-existent unless I made a mistake. Do you have any other wishes for this while I am at it aside from arithmetic benchmarks?

**Comment by Ogeon** [comment]
Thanks for looking into it! I'm still not sure what would be most meaningful, except maybe for conversions. At least sRGB <-> linear. That's the only case I have heard being too slow for some use cases, but that may be more meaningful if a lookup table version were to be implemented for comparison.

I partially added this issue as something to investigate. 🙂

**Comment by Ogeon** [comment]
It's probably good to measure a bit of everything. I wasn't sure how I wanted to approach it when I wrote the description, but I'll edit it to be clear about being more general and open up for discussion.

A good candidate that came up today is to measure the time it takes to convert between color spaces. That's also something I believe may still have room for improvement.

More suggestions are welcome!

**Comment by okaneco** [comment]
Sounds good. I wasn't sure which issue to post under as I also timed Srgb to LinSrgb and this seemed more specific. https://github.com/Ogeon/palette/issues/126#issuecomment-612602250

That action looks interesting, I wonder how noisy benches are on CI.

For initial coverage, I imagine there should be documentation to explain which colors link to other spaces and be a guideline for what to implement. The major ones being Rgb to Xyz, Xyz to the linear models, and the intermediates along the way. The matrix operations are key to this but they're fairly lean already. I suppose component format conversions should also be looked at.

**Comment by Ogeon** [comment]
It's fine and they are related to each other. I just prefer to split it like this. 🙂

> That action looks interesting, I wonder how noisy benches are on CI.

I'm all for using whichever tool seem to be the most suitable. I suppose arguments for using actions would be that they seem more flexible for things like this and to not put more load on Travis. I have also been meaning to give actions a try anyway, but that doesn't mean they have to be used for this.

> For initial coverage, I imagine there should be documentation to explain which colors link to other spaces and be a guideline for what to implement.

I suppose you mean those that have direct conversion without going through any other space. That would be every manual implementation of `FromColorUnclamped`. I suppose there's no big reason to measure any other path, as it would involve these anyway.

I don't have it mapped out already, but there are generally two clusters (RGB and CIE) that are connected via XYZ. There are also some additional cases, such as when converting from one RGB space to another. There are shortcuts in place to avoid unnecessary work in there.

> The matrix operations are key to this but they're fairly lean already.

That code is ancient, so it may benefit from a reevaluation. Also the more we can do during compile time there, the better. There may be some more constants that can be calculated in advance.

> I suppose component format conversions should also be looked at.

Definitely good to keep an eye on the performance of this. Just changing the data type is hopefully as good as it can get with the new traits. Specific common cases, such as `Srgb<u8>` <-> `LinSrgb<f32>` may be more interesting.

**Comment by Ogeon** [comment]
Another neat tool to consider: https://github.com/marketplace/actions/continuous-benchmark

**Comment by okaneco** [comment]
I did more research and criterion seems best for now because `#[bench]` is unstable and probably won't be stabilized.

What data should the benchmarks use for conversion? Some of the paths have branching conditions and not sure how to hit them. The colormine tests seem like too much data to be useful for a benchmark. Should we generate gradients from arbitrary colors, such as a range from T::zero to T::max_intensity for each (minus the hues), and take n colors?

**Comment by Ogeon** [comment]
That's a tough question. It's good to have a data set that represents what may appear in the "real world", but that's essentially a Utopia at the moment. The colormine set may actually be good start, since it should cover as much as possible, but I don't know if it's going to take ages. The alternative is cherry picking, random or ranges/gradients, I suppose.

I haven't looked at it enough to know what works.

**Comment by okaneco** [comment]
I'm seeing some exciting results in the matrix multiplications already after getting the benchmarking set up. Easy wins like putting asserts in to get rid of unnecessary bounds checking, pulling the branch out of the heavy math section in the matrix inversion, and turning 8 divisions into 8 multiplications by 1 inverse. `thrpt` is the throughput of the colormine data color conversions, how many elements are converted per second. I've started another branch to stash these until some CI check is set up to compare to the baseline. https://github.com/okaneco/palette/commit/e916644c48f0e30b1216cded173dd8881f36a934

```python
Matrix functions/matrix_inverse
                        time:   [21.069 ns 21.114 ns 21.160 ns]
                        change: [-27.548% -27.308% -27.078%] (p = 0.00 < 0.05)
                        Performance has improved.

Matrix functions/rgb_to_xyz_matrix
                        time:   [37.199 ns 37.267 ns 37.336 ns]
                        change: [-39.361% -39.111% -38.871%] (p = 0.00 < 0.05)
                        Performance has improved.

Cie family/xyz to lab   time:   [19.332 us 19.364 us 19.398 us]
                        thrpt:  [7.2172 Melem/s 7.2297 Melem/s 7.2420 Melem/s]
                 change:
                        time:   [-39.057% -30.096% -22.533%] (p = 0.00 < 0.05)
                        thrpt:  [+29.087% +43.053% +64.086%]
                        Performance has improved.

Cie family/linsrgb to xyz
                        time:   [4.5969 us 4.6055 us 4.6151 us]
                        thrpt:  [30.335 Melem/s 30.398 Melem/s 30.455 Melem/s]
                 change:
                        time:   [-26.349% -26.029% -25.678%] (p = 0.00 < 0.05)
                        thrpt:  [+34.550% +35.188% +35.775%]
                        Performance has improved.

Rgb family/xyz to linsrgb
                        time:   [8.8887 us 8.9046 us 8.9219 us]
                        thrpt:  [15.692 Melem/s 15.722 Melem/s 15.750 Melem/s]
                 change:
                        time:   [-12.769% -12.489% -12.186%] (p = 0.00 < 0.05)
                        thrpt:  [+13.877% +14.271% +14.638%]
                        Performance has improved.

```

**Comment by Ogeon** [comment]
Awesome! Those numbers are really impressive! The kind of low hanging fruit I had hoped for.

Something I just came to think of while looking through the changes you made is that since it's all constant length, it should also be possible to destructure the arrays: `let [c0, c1, /*...*/, c8] = c;`. I wonder how it compares to the asserts and if the compiler is able to just skip the checks by knowing the length of everything (I'm honestly surprised it didn't already). This was not stable back in the day, so it wasn't even an option.
